//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Agency
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelAgency1Entities : DbContext
    {
        private static TravelAgency1Entities _context;
        public TravelAgency1Entities()
            : base("name=TravelAgency1Entities")
        {
        }

        public static TravelAgency1Entities GetContext()
        {
            if (_context == null)
                _context = new TravelAgency1Entities();

            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Коментарий_о_отеле> Коментарий_о_отеле { get; set; }
        public virtual DbSet<Отель> Отель { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Рейсы> Рейсы { get; set; }
        public virtual DbSet<Страна> Страна { get; set; }
        public virtual DbSet<Тип> Тип { get; set; }
        public virtual DbSet<Тур> Тур { get; set; }
        public virtual DbSet<Фото_отелей> Фото_отелей { get; set; }
    }
}
