//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Agency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Коментарий_о_отеле
    {
        public int ID { get; set; }
        public Nullable<int> ОтельID { get; set; }
        public string Текст { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public string Отель { get; set; }
    
        public virtual Отель Отель1 { get; set; }
    }
}
