//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Agency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отель
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Отель()
        {
            this.Коментарий_о_отеле = new HashSet<Коментарий_о_отеле>();
            this.Фото_отелей = new HashSet<Фото_отелей>();
            this.Тур = new HashSet<Тур>();
        }
    
        public int ID { get; set; }
        public string Название { get; set; }
        public Nullable<int> Количество_звезд { get; set; }
        public string Код_страны { get; set; }
        public string Изображение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Коментарий_о_отеле> Коментарий_о_отеле { get; set; }
        public virtual Страна Страна { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Фото_отелей> Фото_отелей { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Тур> Тур { get; set; }
    }
}
