//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_Agency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тур
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Тур()
        {
            this.Тип = new HashSet<Тип>();
            this.Отель = new HashSet<Отель>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Количество_билетов { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
        public Nullable<bool> Актуальность { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> РейсID { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Рейсы Рейсы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Тип> Тип { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отель> Отель { get; set; }
    }
}
